---
title: "Covid-Analysis"
author: "Ebenezer Tetteh"
date: "`r Sys.Date()`"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load libraries
library(tibble)
library(readr)
library(dplyr)
```
### Step 1: Load and explore the COVID-19 dataset using readr and tibble
```{r load_data, echo=TRUE}
#Loading the dataset
covid_data <- read_csv("tested_worldwide.csv")
#show structure of the data
glimpse(covid_data)
#show the first 6 records of the dataset
head(covid_data)
#check if there is any missing data in the dataset
any(is.na(covid_data))
#Total number of missing data in the dataset
sum(is.na(covid_data))
#Missing values per column
colSums(is.na(covid_data))
#columns names
names(covid_data)
```

### Step2: Filter and select relevant data using dplyr functions
```{r select-clean}
#selecting the relevant columns
covid_selected <- covid_data %>% 
  select(Date, Country_Region, positive,
  daily_tested, daily_positive, total_tested)
#Remove the rows with missing vales in total_tested and positve
covid_clean <- covid_selected %>% 
  filter(!is.na(positive) & !is.na(total_tested))
#Preview cleaned data
glimpse(covid_clean)
#Confirm there are no missing values in positive and total_tested
colSums(is.na(covid_clean))
```
### Step3: Aggregate data by country and calculate summary statistics
```{r summary statistics}
#Grouping by countries and calculating the total
covid_summary <- covid_clean %>% group_by(Country_Region) %>%
  summarize(total_tested = sum(total_tested, na.rm = TRUE), total_positive = sum(positive, na.rm = TRUE))
#Adding the positivity rate
covid_summary <- covid_summary %>% 
  mutate(positivity_rate = (total_positive / total_tested)*100)
#view result
head(covid_summary)
```

### Step4: Identify top countries by testing numbers and positive case ratios
```{r top-countries}
#Top 10 countries by number of test
top_tested <- covid_summary %>% arrange(desc(total_tested)) %>% slice_head(n=10)
top_tested
#Top 10 countries by positivity rate(only countries with at least 100,000 tests)
top_positive_rate <- covid_summary %>% filter(total_tested >= 100000) %>% arrange(desc(positivity_rate)) %>% slice_head(n=10) 
top_positive_rate
```